env:
    node: true
    es2021: true
    jest: true

parser: '@typescript-eslint/parser'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'

parserOptions:
    ecmaVersion: latest
    sourceType: module
plugins:
    - '@typescript-eslint'
    - 'import'
    - 'jest'

rules:
    {
        '@typescript-eslint/explicit-module-boundary-types': 'off',
        '@typescript-eslint/ban-ts-comment': 'off',
        '@typescript-eslint/no-empty-function': 'off'
    }
