name: Test, lint and compile

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node: [14, 15, 16]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm run test
            - run: npm run lint
